name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2

    - name: Build Gatsby project and deploy to github pages
      run: gatsby build --verbose && gh-pages -d public -b gh-pages
